_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 30
experiments_directory:
    value: /cluster/tufts/hugheslab/eharve06/understanding-SNGP/experiments/ImageNet
kappa:
    value: 19.948244061859228
lr_0:
    value: 0.1
model_name:
    value: RFF_epochs=30_lr_0=0.1_random_state=1001
num_workers:
    value: 16
random_state:
    value: 1001
wandb:
    value: true
wandb_project:
    value: understanding-SNGP
